import type { VideoTutorial } from "./types";

// Placeholder catalogue — replace `id`/URLs with real recordings when available.
export const VIDEOS: VideoTutorial[] = [
  {
    id: "v-intro",
    title: "Portal orientation for development partners",
    description:
      "A guided walk through the public site and your dashboard, and how the pieces connect.",
    duration: "9:40",
    category: "getting-started",
    guide: "welcome-to-the-portal",
    featured: true,
    status: "available",
    chapters: [
      { time: "0:00", label: "What the portal is for" },
      { time: "2:10", label: "The public site" },
      { time: "5:30", label: "Your dashboard" },
      { time: "8:15", label: "Where to get help" },
    ],
  },
  {
    id: "v-invite",
    title: "Accepting your invite in three minutes",
    description: "Set up your account and understand the consent agreement.",
    duration: "3:15",
    category: "getting-started",
    guide: "accept-your-invite",
    status: "available",
    chapters: [
      { time: "0:00", label: "The invite email" },
      { time: "1:05", label: "Consent agreement" },
      { time: "2:20", label: "Password and sign-in" },
    ],
  },
  {
    id: "v-upload",
    title: "Uploading a dataset from start to finish",
    description:
      "Every step of the wizard with a real CSV, ending in Submit for review.",
    duration: "14:20",
    category: "contribute",
    guide: "upload-your-first-dataset",
    featured: true,
    status: "available",
    chapters: [
      { time: "0:00", label: "Before you start" },
      { time: "1:30", label: "Basic info and tags" },
      { time: "4:45", label: "Coverage and indicators" },
      { time: "7:10", label: "Attaching files" },
      { time: "9:30", label: "Governance and licence" },
      { time: "11:40", label: "Visibility and submit" },
    ],
  },
  {
    id: "v-metadata",
    title: "Metadata that gets approved first time",
    description: "Good and bad examples of every field, side by side.",
    duration: "11:05",
    category: "contribute",
    guide: "metadata-field-guide",
    status: "available",
    chapters: [
      { time: "0:00", label: "Titles and descriptions" },
      { time: "3:20", label: "Methodology and limitations" },
      { time: "7:45", label: "Common revision triggers" },
    ],
  },
  {
    id: "v-review",
    title: "How review works — and how to speed it up",
    description: "The six stages, what each reviewer checks, and how to reply to feedback.",
    duration: "7:30",
    category: "contribute",
    guide: "after-you-submit",
    status: "available",
    chapters: [
      { time: "0:00", label: "The pipeline" },
      { time: "2:40", label: "The 8-dimension QA checklist" },
      { time: "5:50", label: "Responding to revisions" },
    ],
  },
  {
    id: "v-team",
    title: "Managing your team and access requests",
    description: "Invites, roles, and approving restricted-dataset requests.",
    duration: "8:10",
    category: "manage",
    guide: "invite-your-team",
    status: "available",
    chapters: [
      { time: "0:00", label: "Inviting members" },
      { time: "3:00", label: "Roles" },
      { time: "5:20", label: "Approving access requests" },
    ],
  },
  {
    id: "v-analytics",
    title: "Reading the analytics dashboard",
    description:
      "Indicators, measure kinds, trends, ward drill-down, and exporting to CSV.",
    duration: "16:45",
    category: "explore",
    guide: "read-the-analytics-dashboard",
    status: "available",
    chapters: [
      { time: "0:00", label: "Choosing an indicator" },
      { time: "4:20", label: "Trends and seasonality" },
      { time: "8:40", label: "LGA ranking and outliers" },
      { time: "13:10", label: "Filters and export" },
    ],
  },
  {
    id: "v-maps",
    title: "Which map should I use?",
    description: "A tour of the four maps and the questions each one answers.",
    duration: "10:25",
    category: "explore",
    guide: "use-the-maps",
    status: "available",
    chapters: [
      { time: "0:00", label: "Coverage map" },
      { time: "2:30", label: "Population, facility, disease layers" },
      { time: "6:10", label: "Facility finder" },
      { time: "8:20", label: "Settlement access" },
    ],
  },
  {
    id: "v-qgis",
    title: "From portal download to a finished map in QGIS",
    description: "Load a GeoPackage, join a CSV, and export a choropleth.",
    duration: "22:00",
    category: "gis",
    guide: "open-portal-data-in-qgis",
    status: "coming-soon",
    chapters: [
      { time: "0:00", label: "Installing QGIS" },
      { time: "3:10", label: "Adding the layer" },
      { time: "9:00", label: "Joining tables" },
      { time: "15:30", label: "Styling and export" },
    ],
  },
];
