import {
  Archive,
  BarChart3,
  BookOpen,
  Database,
  Eye,
  FileCheck,
  FileText,
  GraduationCap,
  KeyRound,
  Layers,
  LayoutDashboard,
  Mail,
  Map,
  RefreshCw,
  Rocket,
  Search,
  ShieldCheck,
  Sparkles,
  Tags,
  Target,
  Upload,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { MetricTone } from "@/components/data/metric-card";
import type { GuideCategory, LearningIconKey } from "@/lib/learning/types";

export const LEARNING_ICONS: Record<LearningIconKey, LucideIcon> = {
  book: BookOpen,
  rocket: Rocket,
  layout: LayoutDashboard,
  "file-check": FileCheck,
  upload: Upload,
  tags: Tags,
  eye: Eye,
  workflow: Workflow,
  refresh: RefreshCw,
  archive: Archive,
  users: Users,
  key: KeyRound,
  target: Target,
  "file-text": FileText,
  search: Search,
  "bar-chart": BarChart3,
  map: Map,
  sparkles: Sparkles,
  layers: Layers,
  database: Database,
  shield: ShieldCheck,
  mail: Mail,
  graduation: GraduationCap,
};

export const CATEGORY_TONE: Record<GuideCategory, MetricTone> = {
  "getting-started": "primary",
  contribute: "success",
  manage: "info",
  explore: "warning",
  gis: "muted",
};
